Update registrarmodule.php
WHMCS/sample-registrar-module pull request #12
Opened 2022-07-07 14:48 UTC by Remitur

Fixed a bug in registrarmodule_GetNameservers (the first element of the result was a "success" element, but it seems that it was used only by very old versions of WHMCS: currently, and with a number of WHMCS versions, it gives an error in client area.
See also here:  https://whmcs.community/topic/315797-domain-nameservers-not-returned-correctly/

2022-07-07 23:53 UTC, WHMCSPeter requested changes
Hello,

Thank you for your suggestion. I have confirmed that this is indeed an issue and your change is good however, could you please amend your commit to completely remove the whitespace?

Once that's done, I'll be happy to merge in this change.

Thanks,

Peter
WHMCS Developer II

2022-07-08 14:28 UTC, Remitur commented
Whitespace removed.
(It's just a matter of coding style: when a single line of code is removed, I find it's better to leave it empty because by doing so the line numbers are unchanged, making the comparison easier with derived code. But it's just my own opinion...)

regards

Remitur

2022-07-08 14:36 UTC, WHMCSPeter approved these changes

2022-07-08 14:37 UTC, WHMCSPeter commented
Thanks for the change. I agree, it can make the diff cleaner and easier to read however, we do try to avoid unnecessary whitespace where possible.

Thanks so much for making that change. I'll go ahead and merge this now.

2022-07-08 14:37 UTC, merged